name: EnderChestViewer
version: 1.4.9
author: D4rKDeagle
main: me.darkdeagle.bukkit.enderchestviewer.EnderChestViewer
commands:
  enderchestviewer:
    description: This command allows you to see other players EnderChest Inventory.
    aliases: [ecv]
permissions:
  enderchestviewer.viewothers:
    default: op
    description: This permission allows you to access /enderchestviewer command to access the Enderchest of someone else.
  enderchestviewer.enderchestviewer:
    default: op
    description: This permission allows you to access /enderchestviewer command.
  enderchestviewer.block.*:
    default: op
    description: This permission allows you to interact in all the different ways with ender chests.
    children:
      enderchestviewer.block.craft:
        default: true
        description: Allows you to craft ender chests.
      enderchestviewer.block.place:
        default: true
        description: Allows you to place ender chests.
      enderchestviewer.block.use:
        default: true
        description: Allows you to use (open) ender chests.
      enderchestviewer.block.break:
        default: true
        description: Allows you to break ender chests.